### ISSUE TITLE
Database Schema

### ISSUE THREAD

**Issue by linakherchi** [jtom2388/Venmo_clone_full_stack_project#1]
- [ ] Contains correct datatypes 
- [ ] Contains appropriate constraints/details
    - [x] primary key
    - [x] not null 
    - [ ] unique
    - [ ] indexed
    - [ ] foreign key
- [ ] Contains bullet points after the table that state which foreign keys will reference to which table, or references to the associations which will be made
    - [ ] foreign key and table name are lowercased, snake_cased and back_ticked
- [ ] Correctly formatted
    - [x] schema is written in a table format
    - [ ] the table's name are lowercased, snake_cased and back_ticked
    - [x] the table header column names are bolded
    - [ ] columns names are lowercased and snaked_cased and back_ticked

**Comment by linakherchi** [comment]
Thank you, Jordan ! 
Do you want your balance to have an integer data type or a float ? 
Please refer to the checklist to add the appropriate modifications, and use Bluebird as a reference.
A couple of constraints are still missing. i.e you want to index your session_token and make it unique.

**Comment by jtom2388** [comment]
Hi Lina,

Thanks for your feedback. I will look into this today.

Jordan
